local EasyLists = {
	ListNames = {
		"Peanut",
		"Sun",
		"Happy",
		"Snow",
		"Water",
		"Tree",
		"Phone",
		"Book",
		"Sky",
		"Road",
		"Fire",
		"Rain",
		"Star",
		"Blue",
		"Green",
		"Cup",
		"Door",
		"Light",
		"Sand",
		"Home",
		"Gold",
		"Black",
		"Hand",
		"Foot",
		"Eye",
		"Air",
		"Stone",
		"Mail",
		"Bird",
		"Moon",
		"Paper",
		"Wind",
		"Day",
		"Night",
		"Base",
		"Cloud",
		"Hot",
		"Ball",
	},

	Peanut = {
		Order = {"Butter", "Fly", "Away"},
		Butter = "B _ _ _ _ _",
		Fly = "F _ _",
		Away = "A _ _ _"
	},

	Sun = {
		Order = {"Set", "Sail", "Boat"},
		Set = "S _ _",
		Sail = "S _ _ _",
		Boat = "B _ _ _"
	},

	Happy = {
		Order = {"Birthday", "Cake", "Mix"},
		Birthday = "B _ _ _ _ _ _ _",
		Cake = "C _ _ _",
		Mix = "M _ _"
	},

	Snow = {
		Order = {"Board", "Walk", "In"},
		Board = "B _ _ _ _",
		Walk = "W _ _ _",
		In = "I _"
	},

	Water = {
		Order = {"Bottle", "Flip", "Phone"},
		Bottle = "B _ _ _ _ _",
		Flip = "F _ _ _",
		Phone = "P _ _ _ _",
	},

	Tree = {
		Order = {"House", "Party", "Animal"},
		House = "H _ _ _ _",
		Party = "P _ _ _ _",
		Animal = "A _ _ _ _ _",
	},

	Phone = {
		Order = {"Call", "Back", "Pack"},
		Call = "C _ _ _",
		Back = "B _ _ _",
		Pack = "P _ _ _",
	},

	Book = {
		Order = {"Club", "Room", "Mate"},
		Club = "C _ _ _",
		Room = "R _ _ _",
		Mate = "M _ _ _"
	},

	Sky = {
		Order = {"Dive", "Gear", "Box"},
		Dive = "D _ _ _",
		Gear = "G _ _ _",
		Box = "B _ _"
	},

	Road = {
		Order = {"Trip", "Wire", "Tap"},
		Trip = "T _ _ _",
		Wire = "W _ _ _",
		Tap = "T _ _",
	},

	Fire = {
		Order = {"Place", "Mat", "Ball"},
		Place = "P _ _ _ _",
		Mat = "M _ _",
		Ball = "B _ _ _"
	},

	Rain = {
		Order = {"Drop", "Down", "Town"},
		Drop = "D _ _ _",
		Down = "D _ _ _",
		Town = "T _ _ _"
	},

	Star = {
		Order = {"Fish", "Tank", "Top"},
		Fish = "F _ _ _",
		Tank = "T _ _ _",
		Top = "T _ _"
	},

	Blue = {
		Order = {"Bird", "Cage", "Fight"},
		Bird = "B _ _ _",
		Cage = "C _ _ _",
		Fight = "F _ _ _ _"
	},

	Green = {
		Order = {"Light", "House", "Boat"},
		Light = "L _ _ _ _",
		House = "H _ _ _ _",
		Boat = "B _ _ _"
	},

	Cup = {
		Order = {"Cake", "Walk", "Way"},
		Cake = "C _ _ _",
		Walk = "W _ _ _",
		Way = "W _ _"
	},

	Door = {
		Order = {"Bell", "Ring", "Side"},
		Bell = "B _ _ _",
		Ring = "R _ _ _",
		Side = "S _ _ _"
	},

	Light = {
		Order = {"Bulb", "Frog", "Jump"},
		Bulb = "B _ _ _",
		Frog = "F _ _ _",
		Jump = "J _ _ _"
	},

	Sand = {
		Order = {"Box", "Car", "Pool"},
		Box = "B _ _",
		Car = "C _ _",
		Pool = "P _ _ _"
	},

	Home = {
		Order = {"Work", "Shop", "Lift"},
		Work = "W _ _ _",
		Shop = "S _ _ _",
		Lift = "L _ _ _"
	},

	Moon = {
		Order = {"Light", "Bulb", "Nose"},
		Light = "L _ _ _ _",
		Bulb = "B _ _ _",
		Nose = "N _ _ _"
	},

	Gold = {
		Order = {"Fish", "Bowl", "Game"},
		Fish = "F _ _ _",
		Bowl = "B _ _ _",
		Game = "G _ _ _"
	},

	Black = {
		Order = {"Board", "Game", "Show"},
		Board = "B _ _ _ _",
		Game = "G _ _ _",
		Show = "S _ _ _"
	},

	Hand = {
		Order = {"Bag", "Pipe", "Line"},
		Bag = "B _ _",
		Pipe = "P _ _ _",
		Line = "L _ _ _"
	},

	Foot = {
		Order = {"Ball", "Park", "Bench"},
		Ball = "B _ _ _",
		Park = "P _ _ _",
		Bench = "B _ _ _ _"
	},

	Eye = {
		Order = {"Ball", "Room", "Service"},
		Ball = "B _ _ _",
		Room = "R _ _ _",
		Service = "S _ _ _ _ _ _"
	},

	Air = {
		Order = {"Port", "Hole", "Punch"},
		Port = "P _ _ _",
		Hole = "H _ _ _",
		Punch = "P _ _ _ _"
	},

	Stone = {
		Order = {"Wall", "Paper", "Clip"},
		Wall = "W _ _ _",
		Paper = "P _ _ _ _",
		Clip = "C _ _ _"
	},

	Mail = {
		Order = {"Box", "Spring", "Time"},
		Box = "B _ _",
		Spring = "S _ _ _ _ _",
		Time = "T _ _ _"
	},

	Bird = {
		Order = {"House", "Hold", "Down"},
		House = "H _ _ _ _",
		Hold = "H _ _ _",
		Down = "D _ _ _"
	},

	Paper = {
		Order = {"Back", "Yard", "Sale"},
		Back = "B _ _ _",
		Yard = "Y _ _ _",
		Sale = "S _ _ _"
	},

	Wind = {
		Order = {"Mill", "Stone", "Cold"},
		Mill = "M _ _ _",
		Stone = "S _ _ _ _",
		Cold = "C _ _ _"
	},

	Day = {
		Order = {"Dream", "Land", "Mark"},
		Dream = "D _ _ _ _",
		Land = "L _ _ _",
		Mark = "M _ _ _"
	},

	Night = {
		Order = {"Stand", "Up", "Hill"},
		Stand = "S _ _ _ _",
		Up = "U _",
		Hill = "H _ _ _"
	},

	Base = {
		Order = {"Ball", "Point", "Blank"},
		Ball = "B _ _ _",
		Point = "P _ _ _ _",
		Blank = "B _ _ _ _"
	},

	Cloud = {
		Order = {"Nine", "Teen", "Age"},
		Nine = "N _ _ _",
		Teen = "T _ _ _",
		Age = "A _ _"
	},

	Hot = {
		Order = {"Dog", "House", "Fly"},
		Dog = "D _ _",
		House = "H _ _ _ _",
		Fly = "F _ _"
	},

	Ball = {
		Order = {"Pen", "Name", "Tag"},
		Pen = "P _ _",
		Name = "N _ _ _",
		Tag = "T _ _"
	},
}
return EasyLists